# Generated by Django 3.0 on 2020-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pdf', models.FileField(upload_to='docs/pdfs')),
                ('cover', models.ImageField(blank='True', null='True', upload_to='docs/covers')),
            ],
        ),
    ]
