# Generated by Django 3.0 on 2020-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
